services:
  - type: web
    name: qualiver-whatsapp-interface
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: PORT
        value: 3000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_N8N_BOT_STATUS_WEBHOOK_URL
        sync: false
      - key: VITE_N8N_MESSAGE_WEBHOOK_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
    plan: free 